# pubspec.yaml
name: flutter_application_2 # Your project name
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust to your SDK constraints if needed

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  collection: ^1.17.0 # Ensure this version is suitable or update
  google_fonts: ^6.2.1 # Check for latest version on pub.dev
  flutter_riverpod: ^2.5.1 # <-- ADDED (Check pub.dev for the latest stable version)
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  pie_chart: ^5.4.0
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.5.3
  google_mobile_ads: ^5.3.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Check for latest version
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/money.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  image: assets/icons/money.png