# pubspec.yaml
name: flutter_application_2 # Oder dein Projektname
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Beispiel, passe es an dein SDK an

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  collection: ^1.17.0 # War schon drin oder ggf. hinzufügen/aktualisieren
  google_fonts: ^6.1.0 # <-- HINZUGEFÜGT (prüfe die neueste Version)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Beispiel

flutter:
  uses-material-design: true